name: TestCafe CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install -g typescript testcafe
          npm install testcafe-reporter-html --save-dev

      - name: Create test reports directory
        run: mkdir -p test_reports

      - name: Run TestCafe tests and generate report
        run: |
          npx testcafe chrome src/tests/*.ts --reporter html:test_reports/test-report.html || exit 1
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test_reports
          path: test_reports/*
